version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - VITE_VUE_APP_BACKEND_URL=http://backend:5001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app/backend
    command: npm start

volumes:
  node_modules_frontend:
  node_modules_backend: